# Generated by Django 4.2.7 on 2023-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_enabled_email_auth',
            field=models.BooleanField(default=False, verbose_name='Аутентификация через Email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_enabled_telegram_auth',
            field=models.BooleanField(default=False, verbose_name='Аутентификация через Telegram бота'),
        ),
    ]
