# USER ERROR CODES
ERROR_USER_NOT_FOUND_CODE = 1
ERROR_USER_INCORRECT_PASSWORD_CODE = 2
ERROR_USER_ERROR_RESET_PASSWORD_CODE = 3
ERROR_USER_ERROR_SEND_OTP_CODE = 4
ERROR_USER_ERROR_CHECK_OTP_CODE = 5

# SYSTEM ERROR CODES